// <auto-generated />
namespace WWW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Populate_Membership_Types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Populate_Membership_Types));
        
        string IMigrationMetadata.Id
        {
            get { return "201808110913294_Populate_Membership_Types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
